In [ ]:
import pandas as pd

arr = np.arange(1_000_000)

lst = list(range (1_000_000))

timeit arr*2

715 ms +- 13.2 us per loop

timeit (x*2 for x in lst)

48.8 ms +- 298 us per loop

In [ ]:
import pandas as pd

data= np.array([[1.5, -0.1, 3],
                 [(0, -3, 6.5]])

data
# array([[1.5, -0.1, 3. ],
#                 [(0. , -3. , 6.5]])

data.shape # (2,3)

data.dtype # dtype('float64')

data * 10

# array([[ 15., -1., 30.],

# (0.,-30. , 65.]])

data * data

# elementwise add, same shape

In [ ]:
import pandas as pd

# Create a DataFrame
data = {
    "name": ["Ali", "John", "Sara"],
    "age": [20.0, 21.0, 19.0]
}

df = pd.DataFrame(data)

print("Before:")
print(df)
print(df.dtypes)

# Convert float to integer
df["age"] = df["age"].astype(int)

print("\nAfter:")
print(df)
print(df.dtypes)

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1.dtype)
print(array2.dtype)

if array1.dtype == array2.dtype:
    print("The arrays have the same datatype")
else:
    print("The arrays have different datatypes")

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([1.0, 2.0, 3.0])

print(array1.dtype)
print(array2.dtype)

if array1.dtype == array2.dtype:
    print("Same datatype")
else:
    print("Different datatypes")

In [ ]:
import numpy as np

arr = np.arange(10)

arr[5:8]           # array([5, 6, 7])

arr_slice = arr[5:8]

arr_slice[1] = 12345

arr

# array([0, 1, 2, 3, 4,

#        12, 12345, 12, 8, 91)

# -> the ORIGINAL array changed!

arr slice[:]-64 #bare slice

all three become 64

instead? a real copy in want a

arr[5:8].copy()